In [1]:
import  cv2

In [2]:
import os

In [3]:
import pandas as pd 

In [4]:
import numpy as  np

In [5]:
from tensorflow.keras.preprocessing.image import img_to_array

In [6]:
img_path = "C:/Users/admin/Desktop/Datasets _online/"

In [7]:
img_path+"angry/"

'C:/Users/admin/Desktop/Datasets _online/angry/'

### Angry 

In [8]:
image_names_angry = os.listdir(img_path+"angry/")

In [9]:
image_names_angry

['11647173796_033ff06112_n_face.png',
 '1379351899_7cfa2b0dc4_b_face.png',
 '14187801814_ea89208940_b_face.png',
 '22600236939_54d0e01905_n_face.png',
 '22721287949_65572bea8b_n_face.png',
 '22913025801_2822113219_n_face.png',
 '24063912157_38a4f8d093_b_face.png',
 '2971847861_5c6fe61308_b_face.png',
 '2Q__ (1)_face.png',
 '2Q__ (2)_face.png',
 '2Q__ (3)_face.png',
 '2Q__ (5)_face.png',
 '2Q___face.png',
 '30313832521_d63b8e0dcb_b_face.png',
 '31049558135_aba6aa9495_n_face.png',
 '31779682004_a9efa7d01e_n_face.png',
 '32389337586_9f0fb42512_n_face.png',
 '33824758533_a82fc5b885_b_face.png',
 '372662640_e8dc799d8b_b_face.png',
 '4604139529_c23a5a462a_n_face.png',
 '8640373691_78da29364a_b_face.png',
 '9k_ (1)_face.png',
 '9k_ (2)_face.png',
 '9k_ (3)_face.png',
 '9k_ (4)_face.png',
 '9k_ (5)_face.png',
 '9k_ (8)_face.png',
 '9k__face.png',
 'images (100)_face.png',
 'images (12)_face.png',
 'images (14)_face.png',
 'images (15)_face.png',
 'images (16)_face.png',
 'images (17)_face.png'

In [10]:
len(image_names_angry)

890

In [11]:
img_dataset = []

In [12]:
img_label = []

In [13]:
type(img_dataset)

list

In [14]:
type(img_label)

list

In [15]:
len(img_dataset)

0

In [16]:
len(img_label)

0

In [17]:
import time 

In [18]:
for name in image_names_angry:
    a_image = cv2.imread(img_path+"angry/"+name)
    a_image = cv2.resize(a_image,(48,48))
    a_image = img_to_array(a_image)
    
    img_dataset.append(a_image)
    img_label.append(0)
 

In [19]:
len(img_dataset)

890

In [20]:
len(img_label)

890

### Fear

In [21]:
image_names_fear = os.listdir(img_path+"fear/")

In [22]:
image_names_fear

['2Q__ (2)_face.png',
 '2Q__ (3)_face.png',
 '2Q__ (4)_face.png',
 '2Q__ (5)_face.png',
 '2Q__ (6)_face.png',
 '2Q___face.png',
 '4146739547_c897693482_b_face.png',
 '9k_ (1)_face.png',
 '9k_ (2)_face.png',
 '9k_ (3)_face.png',
 '9k_ (4)_face.png',
 '9k_ (5)_face.png',
 '9k_ (6)_face.png',
 '9k_ (8)_face.png',
 '9k__face.png',
 'images (10)_face.png',
 'images (11)_face.png',
 'images (12)_face.png',
 'images (13)_face.png',
 'images (14)_face.png',
 'images (15)_face.png',
 'images (16)_face.png',
 'images (17)_face.png',
 'images (18)_face.png',
 'images (19)_face.png',
 'images (22)_face.png',
 'images (26)_face.png',
 'images (27)_face.png',
 'images (31)_face.png',
 'images (33)_face.png',
 'images (34)_face.png',
 'images (35)_face.png',
 'images (37)_face.png',
 'images (38)_face.png',
 'images (39)_face.png',
 'images (40)_face.png',
 'images (41)_face.png',
 'images (43)_face.png',
 'images (46)_face.png',
 'images (47)_face.png',
 'images (48)_face.png',
 'images (50)_face.pn

In [23]:
len(image_names_fear)

570

In [24]:
for name in image_names_fear:
    a_image = cv2.imread(img_path+"fear/"+name)
    a_image = cv2.resize(a_image,(48,48))
    a_image = img_to_array(a_image)

    
    img_dataset.append(a_image)
    img_label.append(1)

In [25]:
len(img_dataset)

1460

In [26]:
len(img_label)

1460

### Happy 

In [27]:
image_names_happy = os.listdir(img_path+"happy/")

In [28]:
image_names_happy

['13694565514_c8b8614cb1_w_face.png',
 '138427101_9bb414b109_b_face.png',
 '1484440_8e91738f5c_n_face.png',
 '17017229733_454ede7bf6_n_face.png',
 '20177276302_ae6846fc47_b_face.png',
 '20181944822_62e74e3f24_b_face.png',
 '20958741469_767244862f_b_face.png',
 '2381253427_01de41e043_b_face.png',
 '27323223021_ea6c795db1_b_face.png',
 '27325727639_58dc6be48f_b_face.png',
 '29165268225_888073773a_b_face.png',
 '29972476913_0d39f4f7e1_n_face.png',
 '2Q__ (10)_face.png',
 '2Q__ (11)_face.png',
 '2Q__ (2)_face.png',
 '2Q__ (5)_face.png',
 '2Q__ (6)_face.png',
 '2Q__ (7)_face.png',
 '2Q__ (8)_face.png',
 '2Q___face.png',
 '31875662386_65df018ffc_b_face.png',
 '32362664627_493e37d1bf_n_face.png',
 '364960711_349382e426_b_face.png',
 '364961514_bd6f9388e3_b_face.png',
 '364961554_995f805895_b_face.png',
 '37513119232_3f4aeaa036_b_face.png',
 '43723696112_d270bd33e1_w_face.png',
 '45251146325_60c3635910_n_face.png',
 '4604131637_c982f9c255_n_face.png',
 '4604138769_878839735e_n_face.png',
 '469

In [29]:
len(image_names_happy)

1406

In [30]:
for name in image_names_happy:
    a_image = cv2.imread(img_path+"happy/"+name)
    a_image = cv2.resize(a_image,(48,48))
    a_image = img_to_array(a_image)

    
    img_dataset.append(a_image)
    img_label.append(2)

In [31]:
len(img_dataset)

2866

In [32]:
len(img_label)

2866

In [33]:
pd.DataFrame(img_label)[0].unique()

array([0, 1, 2], dtype=int64)

### Neutral

In [34]:
image_names_neutral = os.listdir(img_path+"neutral/")

In [35]:
image_names_neutral

['1399935340_c2cf2df2dd_n_face.png',
 '14258193821_69d709a217_n_face.png',
 '14861542712_9ce9f8e42a_w_face.png',
 '14867843307_e978f32afe_n_face.png',
 '15238515323_63e05d8a81_n_face.png',
 '15558843883_3769f126b4_b_face.png',
 '15807661717_5af708818f_n_face.png',
 '15933189253_b0a9ecbaf7_b_face.png',
 '16810171117_8955283015_n_face.png',
 '18783517535_b3fe8e0273_b_face.png',
 '2129200062_f5508bbc77_b_face.png',
 '22201338424_74dc97e0a3_n_face.png',
 '22373617808_9abb45d59c_b_face.png',
 '22573591507_ffc4b3d45a_n_face.png',
 '2336502010_8cdd5dff9c_b_face.png',
 '2336502022_33475bb219_b_face.png',
 '23436647549_ec5beda978_b_face.png',
 '23984003405_b015529f7c_w_face.png',
 '244161918_70d96c8dda_b_face.png',
 '2448022238_2428128291_b_face.png',
 '25852550617_357454f230_n_face.png',
 '26331695574_8f91df4da3_n_face.png',
 '26487870406_94e24d8119_n_face.png',
 '26559693133_d2eed3bb11_b_face.png',
 '26639986531_85009ed7d9_b_face.png',
 '27253215798_4243e0c4f2_b_face.png',
 '27394423895_c265c

In [36]:
len(image_names_neutral)

524

In [37]:
for name in image_names_neutral:
    a_image = cv2.imread(img_path+"neutral/"+name)
    a_image = cv2.resize(a_image,(48,48))
    a_image = img_to_array(a_image)

    
    img_dataset.append(a_image)
    img_label.append(3)
    
print("Neutral Images are  Loaded ")

Neutral Images are  Loaded 


In [38]:
len(img_dataset)

3390

In [39]:
len(img_label)

3390

In [40]:
pd.DataFrame(img_label)[0].unique()

array([0, 1, 2, 3], dtype=int64)

### SAD

In [41]:
image_names_sad = os.listdir(img_path+"sad/")

In [42]:
image_names_sad

['13895174901_768e9f188c_n_face.png',
 '15351433722_5651d61cb8_b_face.png',
 '15411613235_05c506b8f2_b_face.png',
 '160519156_1d48dd1827_b_face.png',
 '22585410223_1c45b7fc33_b_face.png',
 '23257791605_dc77bf47c4_n_face.png',
 '2350687283_d0f08d6693_b_face.png',
 '2490858443_fb823517ff_b_face.png',
 '2520264011_95c3a10d4a_n_face.png',
 '26433348200_369ef7e5be_b_face.png',
 '26787692723_727b1de390_b_face.png',
 '27007268928_b28cdd75ed_n_face.png',
 '27360761136_55e0f47d23_b_face.png',
 '27360976336_c08ff13716_b_face.png',
 '2Q__ (1)_face.png',
 '2Q__ (10)_face.png',
 '2Q__ (11)_face.png',
 '2Q__ (12)_face.png',
 '2Q__ (2)_face.png',
 '2Q__ (4)_face.png',
 '2Q__ (5)_face.png',
 '2Q__ (7)_face.png',
 '2Q__ (9)_face.png',
 '3031419395_a04e65749d_b_face.png',
 '31549147738_fe99890010_b_face.png',
 '31671691006_1a20d2cd01_n_face.png',
 '3237475429_7530bd0209_n_face.png',
 '3303335851_baf5163f5c_b_face.png',
 '36230424141_f49b989e2e_b_face.png',
 '364960606_da24d0398e_n_face.png',
 '364960741

In [43]:
len(image_names_sad)

746

In [44]:
for name in image_names_sad:
    a_image = cv2.imread(img_path+"sad/"+name)
    a_image = cv2.resize(a_image,(48,48))
    a_image = img_to_array(a_image)

    
    img_dataset.append(a_image)
    img_label.append(4)
    
print("Sad Images are  Loaded ")

Sad Images are  Loaded 


In [45]:
pd.DataFrame(img_label)[0].unique()

array([0, 1, 2, 3, 4], dtype=int64)

In [46]:
len(img_dataset)

4136

In [47]:
len(img_label)

4136

### Surprise

In [48]:
image_names_surprise = os.listdir(img_path+"surprise/")

In [49]:
image_names_surprise

['2Q__ (1)_face.png',
 '2Q__ (2)_face.png',
 '2Q__ (3)_face.png',
 '2Q__ (4)_face.png',
 '2Q__ (5)_face.png',
 '2Q__ (7)_face.png',
 '2Q___face.png',
 '445722867_cb5bec64e0_b_face.png',
 '49350623811_8ffc185882_b_face.png',
 '9k_ (1)_face.png',
 '9k_ (3)_face.png',
 '9k_ (4)_face.png',
 '9k_ (5)_face.png',
 '9k__face.png',
 'images (100)_face.png',
 'images (13)_face.png',
 'images (16)_face.png',
 'images (2)_face.png',
 'images (20)_face.png',
 'images (21)_face.png',
 'images (22)_face.png',
 'images (23)_face.png',
 'images (24)_face.png',
 'images (27)_face.png',
 'images (3)_face.png',
 'images (33)_face.png',
 'images (34)_face.png',
 'images (35)_face.png',
 'images (36)_face.png',
 'images (37)_face.png',
 'images (39)_face.png',
 'images (4)_face.png',
 'images (40)_face.png',
 'images (42)_face.png',
 'images (44)_face.png',
 'images (45)_face.png',
 'images (47)_face.png',
 'images (48)_face.png',
 'images (49)_face.png',
 'images (50)_face.png',
 'images (51)_face.png',
 '

In [50]:
len(image_names_surprise)

775

In [51]:
for name in image_names_surprise:
    a_image = cv2.imread(img_path+"surprise/"+name)
    a_image = cv2.resize(a_image,(48,48))
    a_image = img_to_array(a_image)

    
    img_dataset.append(a_image)
    img_label.append(5)
    
print("Surprise Images are  Loaded ")

Surprise Images are  Loaded 


In [52]:
len(img_dataset)

4911

In [53]:
len(img_label)

4911

In [54]:
pd.DataFrame(img_label)[0].unique()

array([0, 1, 2, 3, 4, 5], dtype=int64)

### disgust

In [55]:


image_names_disgust = os.listdir(img_path+"disgust/")

In [56]:
image_names_disgust

['2Q__ (1)_face.png',
 '2Q__ (2)_face.png',
 '2Q__ (3)_face.png',
 '2Q__ (4)_face.png',
 '2Q__ (5)_face.png',
 '2Q__ (6)_face.png',
 '2Q___face.png',
 '364961330_35f505a386_b_face.png',
 '4403432645_b887b43740_n_face.png',
 '445720772_72a9048822_b_face.png',
 '453048985_18d7c41e89_b_face.png',
 '6247018181_17c34048da_b_face.png',
 '9k_ (1)_face.png',
 '9k_ (4)_face.png',
 '9k_ (5)_face.png',
 '9k_ (6)_face.png',
 '9k_ (8)_face.png',
 '9k__face.png',
 'images (14)_face.png',
 'images (16)_face.png',
 'images (19)_face.png',
 'images (20)_face.png',
 'images (22)_face.png',
 'images (23)_face.png',
 'images (24)_face.png',
 'images (28)_face.png',
 'images (32)_face.png',
 'images (33)_face.png',
 'images (34)_face.png',
 'images (40)_face.png',
 'images (42)_face.png',
 'images (43)_face.png',
 'images (48)_face.png',
 'images (5)_face.png',
 'images (50)_face.png',
 'images (54)_face.png',
 'images (55)_face.png',
 'images (58)_face.png',
 'images (61)_face.png',
 'images (66)_face.png

In [57]:
for name in image_names_disgust:
    a_image = cv2.imread(img_path+"disgust/"+name)
    a_image = cv2.resize(a_image,(48,48))
    a_image = img_to_array(a_image)

    
    img_dataset.append(a_image)
    img_label.append(6)
    
print("Disgust Images are  Loaded ")

Disgust Images are  Loaded 


In [58]:
len(img_dataset)

5350

In [59]:
len(img_label)

5350

In [60]:
pd.DataFrame(img_label)[0].unique()

array([0, 1, 2, 3, 4, 5, 6], dtype=int64)

In [61]:
Exp_label = ["Angry", "Fear", "Happy", "Neutral", "Sad", "Surprise", "Disgust"]

In [62]:
Exp_label

['Angry', 'Fear', 'Happy', 'Neutral', 'Sad', 'Surprise', 'Disgust']

### img_dataset  --- >   X
### Img_label  ---->  y

In [63]:
type(img_dataset)

list

In [64]:
type(img_label)

list

In [65]:
img_dataset_array = np.array(img_dataset, dtype = "float")

In [66]:
img_label_array = np.array(img_label)

In [67]:
type(img_dataset_array)

numpy.ndarray

In [68]:
type(img_label_array)

numpy.ndarray

In [69]:
img_dataset_array.max()

255.0

In [70]:
img_dataset_array.min()

0.0

### Scale

In [71]:
img_dataset_scale  = img_dataset_array/255.0

In [72]:
img_dataset_array.max()

255.0

In [73]:
img_dataset_scale.max()

1.0

In [74]:
img_dataset_scale.min()

0.0

###  Splitting of  Dataset along with Label

In [75]:
from sklearn.model_selection import train_test_split

In [76]:
Xtrain, Xtest, ytrain, ytest = train_test_split(img_dataset_scale, img_label_array, test_size=0.25)

In [77]:
Xtrain.shape, Xtest.shape, img_dataset_scale.shape

((4012, 48, 48, 3), (1338, 48, 48, 3), (5350, 48, 48, 3))

In [79]:
ytrain.shape, ytest.shape, img_label_array.shape

((4012,), (1338,), (5350,))

### CNN - Sequential  Model

In [83]:
from tensorflow.keras.models import Sequential

In [84]:
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dropout, BatchNormalization, Dense, Flatten

In [175]:
cnn_smodel= Sequential()

### First Convolutional Layer

In [176]:
cnn_smodel.add( Conv2D(32, (3,3), activation  ="relu", strides = (1,1), 
                padding = "valid", input_shape = (48,48,3))  )


cnn_smodel.add( MaxPooling2D((2,2), strides = 2, padding = "valid"))

cnn_smodel.add(Dropout(0.20))

cnn_smodel.add(BatchNormalization(axis =-1))

### Second Convolutional Layer

In [177]:
cnn_smodel.add( Conv2D(16, (3,3), activation  ="relu", strides = (1,1), padding = "valid")  )

cnn_smodel.add( MaxPooling2D((2,2), strides = 2, padding = "valid"))

cnn_smodel.add(Dropout(0.20))

cnn_smodel.add(BatchNormalization(axis =-1))

### Third Convolutional Layer

In [178]:
cnn_smodel.add( Conv2D(32, (3,3), activation  ="relu", strides = (1,1), padding = "valid")  )

cnn_smodel.add( MaxPooling2D((2,2), strides = 2, padding = "valid"))

cnn_smodel.add(Dropout(0.20))

cnn_smodel.add(BatchNormalization(axis =-1))

### Fully Connected Layer  - ANN

In [179]:
cnn_smodel.add(Flatten())

In [180]:
cnn_smodel.add(Dense(64, activation = "relu"))

In [181]:
cnn_smodel.add(Dense(32, activation = "relu"))

In [182]:
cnn_smodel.add(Dense(16, activation = "relu"))

In [183]:
cnn_smodel.add(Dense(32, activation = "relu"))

In [184]:
cnn_smodel.add(Dense(64, activation = "relu"))

In [185]:
cnn_smodel.add(Dense(7, activation = "softmax"))

In [186]:
cnn_smodel.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_19 (Conv2D)          (None, 46, 46, 32)        896       
                                                                 
 max_pooling2d_15 (MaxPoolin  (None, 23, 23, 32)       0         
 g2D)                                                            
                                                                 
 dropout_15 (Dropout)        (None, 23, 23, 32)        0         
                                                                 
 batch_normalization_15 (Bat  (None, 23, 23, 32)       128       
 chNormalization)                                                
                                                                 
 conv2d_20 (Conv2D)          (None, 21, 21, 16)        4624      
                                                                 
 max_pooling2d_16 (MaxPoolin  (None, 10, 10, 16)      

In [187]:
cnn_smodel.compile(
                    
                    optimizer="adam",
                    loss = "sparse_categorical_crossentropy",
                    metrics = ["accuracy"]

                    )

In [188]:
cnn_smodel.fit(Xtrain, ytrain, epochs = 40)

Epoch 1/40
126/126 [==============================] - 13s 92ms/step - loss: 1.8828 - accuracy: 0.2522
Epoch 2/40
126/126 [==============================] - 12s 94ms/step - loss: 1.7925 - accuracy: 0.2946
Epoch 3/40
126/126 [==============================] - 12s 92ms/step - loss: 1.6673 - accuracy: 0.3504
Epoch 4/40
126/126 [==============================] - 12s 92ms/step - loss: 1.5983 - accuracy: 0.3716
Epoch 5/40
126/126 [==============================] - 12s 91ms/step - loss: 1.5568 - accuracy: 0.3931
Epoch 6/40
126/126 [==============================] - 12s 92ms/step - loss: 1.5144 - accuracy: 0.4180
Epoch 7/40
126/126 [==============================] - 11s 91ms/step - loss: 1.4851 - accuracy: 0.4145
Epoch 8/40
126/126 [==============================] - 12s 92ms/step - loss: 1.4522 - accuracy: 0.4310
Epoch 9/40
126/126 [==============================] - 12s 93ms/step - loss: 1.4214 - accuracy: 0.4305
Epoch 10/40
126/126 [==============================] - 12s 92ms/step - loss: 1.406

In [ ]:
cnn_smodel.evaluate(Xtest,ytest)

In [ ]:
Xtrain.shape

In [ ]:
Xtrain[1111]

In [ ]:
Xtrain.shape

In [ ]:
Xtrain[1111].shape

In [ ]:
Xtrain[1111].reshape(1,48,48,3).shape

In [ ]:
pred = cnn_smodel.predict(Xtrain[1111].reshape(1,48,48,3))

In [ ]:
pred

In [ ]:
pred.argmax(axis= 1)

In [ ]:
Exp_label[3]

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.imshow(Xtrain[1111])

In [ ]:
ytrain[1111]

In [ ]:
Xtest.shape

In [ ]:
Xtest[842]

In [ ]:
Exp_label[ cnn_smodel.predict(Xtest[842].reshape(1,48,48,3)).argmax(axis = -1)[0]]

In [ ]:
plt.imshow(Xtest[842])

In [ ]:
ytest[842]

In [ ]:
Exp_label[3]